### ISSUE TITLE
Error with Blender 2.90 (Linux 64): keyword "apply_as" unrecognized

### ISSUE THREAD

**Issue by cycyx** [ecaroth/blender-mini-base-tools-plugin#1]
When using the plugin with Blender 2.90, the simple bevel works fine, but it's impossible to create Channeled Bevel (1 inch or more).
The result is usually a huge cube and an error message:
Traceback (most recent call last):
  File "/home/cycyx/.config/blender/2.90/scripts/addons/ec3d_bases.py", line 526, in execute
    channelCutout(context, obj, is_large=False)
  File "/home/cycyx/.config/blender/2.90/scripts/addons/ec3d_bases.py", line 327, in channelCutout
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier=obj_cut_mod)
  File "/usr/share/blender/2.90/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1

**Comment by ecaroth** [comment]
Fix just pushed to master

**Comment by cycyx** [comment]
Thx!
